### ISSUE TITLE
Sparse representation is too big

### ISSUE THREAD

**Issue by bocharov** [axiomhq/hyperloglog#21]
I'm counting unique metrics accross different dimensions, and the number of used HLLs can go up to several millions (e.g. number of unique IPs for each user agent or vice versa).
It seems that even empty hyperloglog.Sketch will allocate at least 2^14 = 16384 bytes for the sparseList, which is quite a lot. Redis hyperloglog has way better memory footprint for small cardinalities - http://download.redis.io/redis-stable/src/hyperloglog.c
I wonder if it will be possible to align / merge these two approaches.

**Comment by bocharov** [comment]
Section 5.3.4 Space Efficiency of the paper https://storage.googleapis.com/pub-tools-public-publication-data/pdf/40671.pdf states that:

> For instance, for precision 14, storing every element in the sparse representation as an integer would require 32 bits. The variable length encoding reduces this to an average of 19.49 bits per element. Additionally introducing a difference encoding requires 11.75 bits per element and using the improved encoding of hash values further decreases this value to 8.12 bits on average.

**Comment by maciej** [comment]
I've reproduced the issue you mentioned with the following code:

```
go
func Benchmark_Size_0(b *testing.B) {
	var sk *Sketch
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		sk, _ = newSketch(16, true)
	}
	_ = sk
}
```

```
Benchmark_Size_0-8   	  210655	      6247 ns/op	   65664 B/op	       4 allocs/op
```

The issue is due to compressed list pre-allocating the compressed buffer [1].

I think that shouldn't be this way. The sole reason for having a compressed HLL representation is to save memory, even at the expense of higher CPU utilization (eg due to later reallocations).

[1] https://github.com/axiomhq/hyperloglog/blob/master/compressed.go#L108
